spring:
  application:
    name: backblog

  datasource:
    url: jdbc:postgresql://localhost:5432/backblog
    username: postgres
    password: windows99
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 15MB  # Definindo um limite superior para garantir que o upload funcione
      max-request-size: 15MB  # Ajuste conforme necess√°rio para acomodar arquivos grandes

file:
  upload-dir: /home/sw/Documentos/trabalho/blogback/src/main/resources/static/uploads
